[package]
name = "aep_schedule_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["rlib"]

[profile.release]
lto = true
codegen-units = 1
strip = true

[profile.dev]
opt-level = 3
debug = true

[dev-dependencies]
criterion = { version = "0.6", features = ["html_reports"] }

[[bench]]
name = "generator"
harness = false

[dependencies]
compact_str = { version = "0.9", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive", "rc"] }
icalendar = "0.16"
chrono = { version = "0.4.38", features = ["serde"] }
log = "0.4.21"
