[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["rlib"]

[dependencies]
leptos = { workspace = true, features = [ "ssr" ]}
leptos_axum.workspace = true

generator = { path = "../generator" }
axum.workspace = true
tokio.workspace = true
reqwest.workspace = true
